package dvdrental;
// Generated 2/03/2016 07:35:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private BigDecimal numCuentaEst;
     private String nombreEst;
     private String materias;

    public Estudiante() {
    }

	
    public Estudiante(BigDecimal numCuentaEst) {
        this.numCuentaEst = numCuentaEst;
    }
    public Estudiante(BigDecimal numCuentaEst, String nombreEst, String materias) {
       this.numCuentaEst = numCuentaEst;
       this.nombreEst = nombreEst;
       this.materias = materias;
    }
   
    public BigDecimal getNumCuentaEst() {
        return this.numCuentaEst;
    }
    
    public void setNumCuentaEst(BigDecimal numCuentaEst) {
        this.numCuentaEst = numCuentaEst;
    }
    public String getNombreEst() {
        return this.nombreEst;
    }
    
    public void setNombreEst(String nombreEst) {
        this.nombreEst = nombreEst;
    }
    public String getMaterias() {
        return this.materias;
    }
    
    public void setMaterias(String materias) {
        this.materias = materias;
    }




}


