package dvdrental;
// Generated 2/03/2016 07:35:47 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private BigDecimal idUsuario;
     private String contrasena;
     private String correo;
     private BigDecimal numCuenta;

    public Usuario() {
    }

    public Usuario(BigDecimal idUsuario, String contrasena, String correo, BigDecimal numCuenta) {
       this.idUsuario = idUsuario;
       this.contrasena = contrasena;
       this.correo = correo;
       this.numCuenta = numCuenta;
    }
   
    public BigDecimal getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(BigDecimal idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public BigDecimal getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(BigDecimal numCuenta) {
        this.numCuenta = numCuenta;
    }




}


